# Generated by Django 4.2 on 2025-08-13 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codes', '0003_alter_otpcode_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpcode',
            name='number',
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
